from collections.abc import Mapping, Sequence
from typing import Any

JsonData = Mapping[str, Mapping[str, Any]]

class Layout:
    @staticmethod
    def from_file(path: str) -> Layout: ...
    @staticmethod
    def from_string(name: str, text: str, *, format: str | None = None) -> Layout: ...
    @property
    def name(self) -> str: ...
    def blocks(self, *names: str) -> list[BuildBlock]: ...

class BuildBlock:
    @property
    def layout_name(self) -> str: ...
    @property
    def name(self) -> str | None: ...

class DataRange:
    @property
    def start_address(self) -> int: ...
    @property
    def used_size(self) -> int: ...
    @property
    def allocated_size(self) -> int: ...
    @property
    def data(self) -> bytes: ...
    # Planned hexy interop after hexy-python is cleaned up and released.
    # def to_hexy(self): ...

class BlockStat:
    @property
    def name(self) -> str: ...
    @property
    def start_address(self) -> int: ...
    @property
    def allocated_size(self) -> int: ...
    @property
    def used_size(self) -> int: ...
    @property
    def checksum_values(self) -> list[int]: ...

class BuildStats:
    @property
    def blocks_processed(self) -> int: ...
    @property
    def total_allocated(self) -> int: ...
    @property
    def total_used(self) -> int: ...
    @property
    def total_duration_ms(self) -> float: ...
    @property
    def block_stats(self) -> list[BlockStat]: ...
    @property
    def space_used_pct(self) -> float: ...

class BuildResult:
    @property
    def ranges(self) -> list[DataRange]: ...
    @property
    def stats(self) -> BuildStats: ...
    @property
    def used_values(self) -> dict[str, Any]: ...
    def to_intel_hex(self, *, record_width: int = 32) -> str: ...
    def to_srec(self, *, record_width: int = 32) -> str: ...
    # Planned hexy interop after hexy-python is cleaned up and released.
    # def to_hexy(self): ...

def build(
    blocks: Sequence[BuildBlock],
    *,
    data: JsonData | None = None,
    json_path: str | None = None,
    xlsx_path: str | None = None,
    variants: Sequence[str] | None = None,
    main_sheet: str = "Main",
    strict: bool = False,
) -> BuildResult: ...
